config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :cohorts
    resources :hidings
    resources :companies
    resources :entries
    resources :job_applications
    resources :offers
    resources :permissions
    resources :positions
    resources :profiles
    resources :salaries
    resources :schools
    resources :users

    root to: "users#index"
  end

  resources :companies, only: [:index, :show]
  resources :users, only: [:show, :index]
  resources :events, only: [:create]
  resources :positions
  resources :job_applications do
    get :autocomplete_company_name, :on => :collection
  end
  resources :offers
  resources :translations do 
    get :autocomplete_project_name, :on => :collection
  end

  get '/profile' => 'profiles#edit', as: "update_profile"
  resources :profiles, only: [:update]

  resources :entries, only: [:show]
  # get '/entries/:id' => 'entries#show', as: :entry

  get '/entries/:id/add_offer' => 'offers#add_new_to_existing_entry', as: :advance_job_application
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/entries/:id/add_position' => 'positions#add_new_to_existing_entry', as: :advance_offer
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/auth/:provider/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  root 'dashboards#show'
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :entry
  has_one :salary

  accepts_nested_attributes_for :entry, :salary

  delegate :user, to: :entry

  enum nature_of_employment: {"internship" => 0, "apprenticeship" => 1, 
                              "freelance/contract" => 2, "part-time" => 3, 
                              "full-time" => 4, "self-employed" => 5}
end

app/controllers/admin/positions_controller.rb
module Admin
  class PositionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Position.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Position.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  
  # GET /positions/new
  # not currently being used
  def new
    @position = Position.new
    @position.build_salary
  end

  # GET /entries/:id/add_position
  def add_new_to_existing_entry
    @position = Position.new
    @position.build_salary
    @entry = Entry.find(params[:id])
    @position.entry_id = @entry.id
    render :new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  def create
    build_position_on_existing_entry
    @position.update(position_params)
    position_save
  end

  # PATCH/PUT /positions/1
  def update
    if @position.update(position_params)
      redirect_to @position, notice: 'Position was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /positions/1
  def destroy
    @position.destroy
    redirect_to positions_url, notice: 'Position was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def position_params
      params.require(:position).permit(:job_title, :location, :nature_of_employment, :remote, :start_date, :end_date, :entry_id,
        entry_attributes: [:id, :user_id, :company_name],
        salary_attributes: [:id, :amount, :rate])
    end

    def build_position_on_existing_entry
      entry = Entry.find(params["position"]["entry_attributes"]["id"])
      @position = entry.build_position
      @position.save
    end

    def position_save
      if @position.save
        create_new_position_event_and_redirect
      else
        render :new
      end
    end

    def create_new_position_event_and_redirect
      Event.for_position(@position)
      redirect_to @position.entry, notice: 'Position was successfully created.'
    end
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
    <p>
      <%= f.label "For which existing application?" %>
      <%= f.select(:entry_id, @entries.collect {|e| [e.company.name, e.id]}) %><br>
    </p>
  <% elsif params[:action] == "add_new_to_existing_entry" %>
    <p>
      <%= f.label @entry.company.name %>
      <%= f.hidden_field :entry_id, :value => @position.entry_id %>
    </p>
  <% end %>

  <p>
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title, value: @entry.offer.job_title %>
  </p>

  <%= f.fields_for :salary do |ff| %>
    <p>
      <%= ff.label :amount, "Salary/Rate" %><br>
      <%= ff.text_field :amount, placeholder: "49,000 or 20/hr" %>
      <%= ff.select(:rate, options_for_select(Salary.rates.keys, "hourly")) %>
    </p>
  <% end %>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location, value: @entry.offer.location %>
  </p>
  <p>
    <%= f.label "Employment type" %><br>
    <%= f.select(:nature_of_employment, options_for_select(Position.nature_of_employments.keys, @entry.offer.nature_of_employment)) %>
  </p>
  <p>
    <label for="offer_remote">
      <%= f.check_box :remote, checked: @entry.offer.remote %>
      Remote?
    </label>
  </p>
  <p>
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, 
          {start_year: Date.today.year - 5, end_year: Date.today.year + 5, 
          :include_blank => true, :default => nil}, class: "dateSelect" %>
  </p>
  <p>
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, 
          {start_year: Date.today.year - 5, end_year: Date.today.year + 5, 
          :include_blank => true, :default => nil}, class: "dateSelect" %>
  </p>

    <%= f.submit "Save" %>
<% end %> 

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Positions</h1>

<table>
  <thead>
    <tr>
      <th>Job title</th>
      <th>Location</th>
      <th>Remote</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.job_title %></td>
        <td><%= position.location %></td>
        <td><%= position.remote %></td>
        <td><%= position.start_date %></td>
        <td><%= position.end_date %></td>
        <td><%= link_to 'Show', position.entry %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: @entry.user} %>
<% end %>

<h1><%= @entry.company.name %>: Position Accepted</h1>

<p>
  You're accepting an offer "<%= @entry.offer.job_title %>" <%= @entry.offer.nature_of_employment %> position, at <%= @entry.company.name %> in <%= @entry.offer.location %>. Congrats!
</p>

<p>
  Please add/confirm some details about the position below.
</p>

<%= render 'form' %>

app/views/positions/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Job title:</strong>
  <%= @position.job_title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @position.location %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @position.remote %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @position.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @position.end_date %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>