config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :cohorts
    resources :hidings
    resources :companies
    resources :entries
    resources :job_applications
    resources :offers
    resources :permissions
    resources :positions
    resources :profiles
    resources :salaries
    resources :schools
    resources :users

    root to: "users#index"
  end

  resources :companies, only: [:index, :show]
  resources :users, only: [:show, :index]
  resources :events, only: [:create]
  resources :positions
  resources :job_applications do
    get :autocomplete_company_name, :on => :collection
  end
  resources :offers
  resources :translations do 
    get :autocomplete_project_name, :on => :collection
  end

  get '/profile' => 'profiles#edit', as: "update_profile"
  resources :profiles, only: [:update]

  resources :entries, only: [:show]
  # get '/entries/:id' => 'entries#show', as: :entry

  get '/entries/:id/add_offer' => 'offers#add_new_to_existing_entry', as: :advance_job_application
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/entries/:id/add_position' => 'positions#add_new_to_existing_entry', as: :advance_offer
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/auth/:provider/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  root 'dashboards#show'
end

app/models/translation.rb
class Translation < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
	attr_accessor :project_name

	scope :finished, -> {where("output_text IS NOT NULL").order("updated_at DESC")}
	scope :unfinished, -> {where("output_text IS NULL").order("created_at DESC")}

	def truncate
		self.input_text[0,50] + " ..."
	end

	def self.unfinished?
		self.unfinished.count > 0
	end

	# def self.finished
	# 	self.where("output_text IS NOT NULL").order("updated_at DESC")
	# end

	# def self.unfinished
	# 	self.where("output_text IS NULL").order("created_at DESC")
	# end

	def icon
		if self.output_text
			"fa fa-check-circle-o finished"
		else
			"fa fa-clock-o unfinished"
		end
	end

	def set_project_from_name(project_name, persist=true)
	  self.project = Project.find_or_create_by(name: project_name)
	  self.save if persist
	end

	def project_name=(input)
	  set_project_from_name(input, false)
	end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
	before_action :set_translation, only: [:show, :edit, :update, :destroy]
	before_action :admin_only, only: [:edit, :index]
	before_action :must_have_candidate_profile, only: [:new, :create]
	autocomplete :project, :name

	def new
		@translation = Translation.new
	end

	def create
		@translation = Translation.new(translation_params)

		if @translation.save
			redirect_to new_translation_path, notice: "Translation request submitted."
		else
			render :new
		end
	end

	def show
	end

	def index
		@finished_translations = Translation.finished
		@new_translations = Translation.unfinished
	end

	def edit
	end
	
	def update
		if @translation.update(translation_params)
			redirect_to translations_path, notice: "Translation saved!"
		else
			render :edit
		end
	end

	def destroy
	end

	private
		def set_translation
      		@translation = Translation.find(params[:id])
    	end

		def translation_params
			params.require(:translation).permit(:user_id, :input_text, :output_text, :project_name)
		end
end

app/views/translations/_edit_form.html.erb
<%= form_for(@translation) do |f| %>
	<% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
	<% end %>

	<fieldset>
    <h2>Work Details</h2>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <p>
      <%= f.label :project_name, @translation.project.name %>
      <%= @translation.input_text %>
    </p>
  </fieldset>
  <fieldset>
    <p>
      <h2>Translation</h2>
      <%= f.text_area :output_text %>
    </p>
  </fieldset>

  <%= f.submit "Submit" %>
<% end %>

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
	<% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
	<% end %>

	<fieldset>
    <h2>Work Details</h2>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <p>
      <%= f.label :project_name, "Project" %>
      <%= f.autocomplete_field :project_name, autocomplete_project_name_translations_path, placeholder: "Project name here" %>
    </p>
    <p>
      <%= f.label :input_text, "Describe the work you did. Be as specific as you can." %>
      <%= f.text_area :input_text %>
    </p>
  </fieldset>

  <%= f.submit "Submit" %>
<% end %>

app/views/translations/edit.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: current_user} %>
<% end %>

<h1>Provide a Translation</h1>

<p>Help <%= @translation.user.name %> translate this item for their resumé.</p>

<%= render 'edit_form' %>

app/views/translations/index.html.erb
<h1>Resumé Translations</h1>

<% @new_translations.each do |translation| %>
  <div class="comment">
    <div class="comment-image">
      <%= image_tag(translation.user.image_url) %>
    </div>

    <div class="comment-content">
      <div class="comment-headline">
        <%= link_to translation.user.name, user_path(translation.user_id) %> submitted a translation request for
        <b><%= translation.project.name %></b>
        <%= time_ago_in_words(translation.created_at) %> ago
      </div>

      <p>
        <em>
          <%= link_to translation.truncate, edit_translation_path(translation.id) %>
        </em>
      </p>
    </div>
  </div>
<% end %>

<% @finished_translations.each do |translation| %>
  <div class="comment comment--closed">
    <div class="comment-image">
      <%= image_tag(translation.user.image_url) %>
    </div>

    <div class="comment-content">
      <div class="comment-headline">
        <%= link_to translation.user.name, user_path(translation.user_id) %> submitted a translation request for
        <b><%= translation.project.name %></b>
        <%= time_ago_in_words(translation.created_at) %> ago
      </div>

      <p>
        <em>
          <%= link_to translation.truncate, translation %>
        </em>
      </p>
    </div>
  </div>
<% end %>

<%# paginate @translations %>

app/views/translations/new.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: current_user} %>
<% end %>

<h1>Submit a Translation Request</h1>

<p>Sometimes, it can feel like you have no way to talk about the work you've done. We don't want that to be nerve-wracking. Tell us some technical work you've done on your projects, and we will help you translate it into resumé speak.</p>

<p>Example:</p>

<p>If you send: "i made it so some users can see certain pages but others can’t. each user has different 'access' privileges."</p>

<p>We'll send back something like: "Implemented role-based authorization using Pundit and Devise to restrict access within application according to authentication policies."</p>

<%= render 'form' %>

app/views/translations/show.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: current_user} %>
<% end %>

<h1>Your Resumé Translation</h1>


<form>
	<fieldset>
		<h2>Work Details</h2>
		<label><%= @translation.project.name %></label>
		<p><%= @translation.input_text %></p>
	</fieldset>
</form>

<% if @translation.output_text %>

	<form>
		<fieldset>
			<h2>Translation</h2>
			<p><%= @translation.output_text %></p>
		</fieldset>
	</form>
<% else %>
	<p>Looks like there's no translation yet. Check back soon, or bug the instructors in Slack.</p>
<% end %>