config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :cohorts
    resources :hidings
    resources :companies
    resources :entries
    resources :job_applications
    resources :offers
    resources :permissions
    resources :positions
    resources :profiles
    resources :salaries
    resources :schools
    resources :users

    root to: "users#index"
  end

  resources :companies, only: [:index, :show]
  resources :users, only: [:show, :index]
  resources :events, only: [:create]
  resources :positions
  resources :job_applications do
    get :autocomplete_company_name, :on => :collection
  end
  resources :offers
  resources :translations do 
    get :autocomplete_project_name, :on => :collection
  end

  get '/profile' => 'profiles#edit', as: "update_profile"
  resources :profiles, only: [:update]

  resources :entries, only: [:show]
  # get '/entries/:id' => 'entries#show', as: :entry

  get '/entries/:id/add_offer' => 'offers#add_new_to_existing_entry', as: :advance_job_application
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/entries/:id/add_position' => 'positions#add_new_to_existing_entry', as: :advance_offer
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/auth/:provider/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  root 'dashboards#show'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :entry
  has_one :salary
  accepts_nested_attributes_for :entry, :salary

  delegate :user, to: :entry

  enum nature_of_employment: {"internship" => 0, "apprenticeship" => 1, 
                              "freelance/contract" => 2, "part-time" => 3, 
                              "full-time" => 4, "self-employed" => 5}
                              
end

app/controllers/admin/offers_controller.rb
module Admin
  class OffersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Offer.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Offer.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  def index
    if current_user.has_view_permission
      @offers = Offer.all
    else
      @offers = current_user.offers
    end
  end

  # GET /offers/1
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @offer.build_salary
    @entries = Entry.all_without_offer
    check_if_new_offer_is_valid
  end

  # GET /entries/:id/add_offer
  def add_new_to_existing_entry
    @offer = Offer.new
    @offer.build_salary
    @entry = Entry.find(params[:id])
    @offer.entry_id = @entry.id
    render :new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  def create
    # @offer = Offer.new(offer_params)
    # Implementing the following to move past an error
    # seemingly caused by a conflict between ANAF and child/parent
    # strong params?
    entry = Entry.find(params["offer"]["entry_attributes"]["id"])
    @offer = entry.build_offer
    @offer.save
    @offer.update(offer_params)
    if @offer.save
      Event.for_offer(@offer)
      redirect_to @offer.entry, notice: 'Offer added.'
    else
      render :new
    end
  end

  # PATCH/PUT /offers/1
  def update
    if @offer.update(offer_params)
      redirect_to @offer.entry, notice: 'Offer updated.'
    else
      render :edit
    end
  end

  # DELETE /offers/1
  def destroy
    @offer.destroy
    redirect_to offers_url, notice: 'Offer deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def offer_params
      params.require(:offer).permit(:job_title, :location, :nature_of_employment, :remote, :entry_id,
      entry_attributes: [:id, :user_id, :company_name],
      salary_attributes: [:id, :amount, :rate])
    end

    def check_if_new_offer_is_valid
      if @entries.length == 0 
        redirect_to offers_path, notice: 'You must first create a job application.'
      end 
    end
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <h2>Company Info</h2>
    <%= f.fields_for :entry do |ff| %>
      <p>
        <%= ff.label :company_name, "Company" %>
        <%= ff.autocomplete_field :company_name, autocomplete_company_name_job_applications_path, placeholder: "Google" %>
      </p>
    <% end %> 

    <p>
      <%= f.label :location %>
      <%= f.text_field :location, placeholder: "Omaha" %>
    </p>  
  </fieldset>

  <fieldset>
    <h2>Offer Details</h2>
    <p>
      <%= f.label :job_title %>
      <%= f.text_field :job_title %>
    </p>

    <%= f.fields_for :salary do |ff| %>
      <p>
        <%= ff.label :amount, "Salary/Rate" %>
        <%= ff.text_field :amount, placeholder: "49,000 or 20/hr" %>
        <%= ff.select(:rate, options_for_select(Salary.rates.keys, "hourly")) %>
      </p>
    <% end %>
    
    <p>
      <%= f.label "Employment type" %>
      <%= f.select(:nature_of_employment, Offer.nature_of_employments.keys) %>
    </p>
    <p>
      <label for="job_application_remote">
        <%= f.check_box :remote %>
        Remote?
      </label>
    </p>  

  </fieldset>

  <%= f.submit "Save" %>
<% end %>

app/views/offers/edit.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: current_user} %>
<% end %>

<h1>Editing Offer</h1>

<p>Update information about the offer you've received below.</p>

<%= render 'form' %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Offers</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Job title</th>
      <th>Location</th>
      <th>Remote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> -->
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.job_title %>, <%= offer.entry.company.name %></td>
        <!-- <td><%= offer.location %></td>
        <td><%= offer.remote %></td> -->
        <td><%= link_to 'Show', offer.entry %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<!--   </tbody> -->
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<% content_for :sidebar do %>
  <%= render "application/default_sidebar", {user: @entry.user} %>
<% end %>

<h1><%= @entry.company.name %>: Offer Received</h1>

<p>
  You're adding an offer for the "<%= @entry.job_application.job_title %>" <%= @entry.job_application.nature_of_employment %> position, at <%= @entry.company.name %> in <%= @entry.job_application.location %>. Congrats!
</p>

<p>
  Please add/confirm some details about the offer below.
</p>

<%= render 'form' %>

app/views/offers/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Job title:</strong>
  <%= @offer.job_title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @offer.location %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @offer.remote %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>