config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :cohorts
    resources :hidings
    resources :companies
    resources :entries
    resources :job_applications
    resources :offers
    resources :permissions
    resources :positions
    resources :profiles
    resources :salaries
    resources :schools
    resources :users

    root to: "users#index"
  end

  resources :companies, only: [:index, :show]
  resources :users, only: [:show, :index]
  resources :events, only: [:create]
  resources :positions
  resources :job_applications do
    get :autocomplete_company_name, :on => :collection
  end
  resources :offers
  resources :translations do 
    get :autocomplete_project_name, :on => :collection
  end

  get '/profile' => 'profiles#edit', as: "update_profile"
  resources :profiles, only: [:update]

  resources :entries, only: [:show]
  # get '/entries/:id' => 'entries#show', as: :entry

  get '/entries/:id/add_offer' => 'offers#add_new_to_existing_entry', as: :advance_job_application
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/entries/:id/add_position' => 'positions#add_new_to_existing_entry', as: :advance_offer
  # probably makes sense to move this controller action to the entries controller at some point?

  get '/auth/:provider/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  root 'dashboards#show'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    if current_user.admin?
      @job_applications = JobApplication.permitted_for(current_user).timeline.page(params[:page])
    else
      @job_applications = current_user.job_applications.order("created_at DESC")
      @translations = current_user.translations.order("created_at DESC")
    end
  end
end

app/views/dashboards/_admin.html.erb
<% @job_applications.each do |job_application| %>
  <div class="comment">
    <div class="comment-image">
      <%= image_tag(job_application.user_photo) %>
    </div>

    <div class="comment-content">
      <div class="comment-headline">
        <%= link_to job_application.name, user_path(job_application.user_id) %> applied to
        <%= link_to job_application.company.name, entry_path(job_application.entry_id) %>
        <%= time_ago_in_words(job_application.created_at) %> ago
      </div>

      <p>
        <%= link_to job_application.job_title, entry_path(job_application.entry_id) %>
        <em>-
          <%= link_to("Job Posting", job_application.posting_url, target: "_blank") unless  job_application.posting_url.blank? %>
        </em>
      </p>
    </div>
  </div>
<% end %>

<%= paginate @job_applications %>

app/views/dashboards/_candidate.html.erb
<% if @job_applications.any? %>
  <table class="tables">
    <% @job_applications.each do |job_application| %>
      <tr>
        <td>
          <%= link_to job_application.job_title, job_application.entry %>,
          <%= job_application.entry.company.name %>
        </td>

        <td>
          <%= link_to("Job Posting", job_application.posting_url, target: "_blank") unless job_application.posting_url.blank? %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>
    Looks like you haven't applied to any jobs yet. When you do, they'll show up here.
  </p>

  <p>
    Click "Add Application" in the menu bar above to get started.
  </p>
<% end %>

<h1>Resumé Translations</h1>

<% if @translations.any? %>
  <table class="tables">
    <% @translations.each do |translation| %>
      <tr>
        <td class="tables__cell">
          <div>
            <%= translation.project.name %> - 
            <%= link_to translation.truncate, translation %>
          </div>
          <i class= "<%= translation.icon %>" aria-hidden="true"></i>
        </td>
      </tr>
    <% end %>
  </table>  
<% end %>

app/views/dashboards/show.html.erb
<h1>Application Dashboard</h1>

<% if current_user.admin? %>
  <%= render "admin" %>
<% else %>
  <%= render "candidate" %>
<% end %>